config/routes.rb
TownParliament::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => "pages#index"

  get "pages/index"
  get "pages/meeting"
  get "/admin" => "admin/base#index", :as => "admin"

  namespace "admin" do
    resources :users
  end

  resources :acts do
    # HTML AND PDF
    get '/html', to: 'acts#html'
    get '/pdf', to: 'acts#pdf'
  end

  resources :amandments

  post '/create_head_intro', to: 'acts#create_head_intro'
  delete '/destroy_head', to:'acts#destroy_head'

  # REGULATION ROUTES
  post '/prepare_regulation', to: 'acts#prepare_regulation'
  post '/create_regulation', to: 'acts#create_regulation'
  delete '/destroy_regulation', to: 'acts#destroy_regulation'

  # SUBJECT ROUTES
  post '/prepare_subject', to: 'acts#prepare_subject'
  post '/create_subject', to: 'acts#create_subject'
  delete '/destroy_subject', to: 'acts#destroy_subject'

  # CLAUSE ROUTES
  post '/prepare_clause', to: 'acts#prepare_clause'
  post '/create_clause', to: 'acts#create_clause'
  delete '/destroy_clause', to: 'acts#destroy_clause'

  # STANCE ROUTES
  post '/prepare_stance', to: 'acts#prepare_stance'
  post '/create_stance', to: 'acts#create_stance'
  delete '/destroy_stance', to: 'acts#destroy_stance'

  # DOT ROUTES
  post '/prepare_dot', to: 'acts#prepare_dot'
  post '/create_dot', to: 'acts#create_dot'
  delete '/destroy_dot', to: 'acts#destroy_dot'

  # SUBDOT ROUTES
  post '/prepare_subdot', to: 'acts#prepare_subdot'
  post '/create_subdot', to: 'acts#create_subdot'
  delete '/destroy_subdot', to: 'acts#destroy_subdot'

  # PARAGRAPH ROUTES
  post '/prepare_paragraph', to: 'acts#prepare_paragraph'
  post '/create_paragraph', to: 'acts#create_paragraph'
  delete '/destroy_paragraph', to: 'acts#destroy_paragraph'

  # SEARCH SHIT
  get :search, to: 'search#index'
  get :perform_search, to: 'search#perform'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!

  def render404
    render :file => File.join(Rails.root, 'public', '404.html'), :status => 404, :layout => false
    return true
  end

  def citizen_only
    unless current_user.citizen?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def alderman_only
    unless current_user.alderman?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def assembly_president_only
    unless current_user.assembly_president?
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, { :sort => column, :direction => direction }, { :class => css_class }
  end

end

app/views/layouts/application/_flash_messages.html.erb
<% if notice %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>

<% if alert %>
  <div class="alert alert-error"><p><%= alert %></p></div>
<% end %>

app/views/layouts/application/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#baseapp-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "Town Parliament", root_path, :class => "navbar-brand" %>
    </div>


    <div class="collapse navbar-collapse" id="baseapp-navbar-collapse-1">

        <% if user_signed_in? %>
          <ul class="nav navbar-nav">

          <li><%= link_to "Search", search_path %></li>

          <li class="dropdown">
            <a class="dropdown-toggle" type="button" data-toggle="dropdown">Acts
              <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "All Acts", acts_path %></li>
              <% if current_user.alderman? %>
                <li><%= link_to "New Act", new_act_path %></li>
              <% end %>
            </ul>
          </li>

          <% if current_user.alderman? %>
            <li class="dropdown">
              <a class="dropdown-toggle" type="button" data-toggle="dropdown">Amandments
                <span class="caret"></span></a>

              <ul class="dropdown-menu">
                <li><%= link_to "All Amandments", amandments_path %></li>
              </ul>
            </li>
          <% end %>

          <% if current_user.assembly_president? %>
            <li><%= link_to "Session", pages_meeting_path %></li>
          <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Account settings", edit_user_registration_path %></li>

          <% if current_user.admin? %>
            <li><%= link_to "Admin", admin_path %></li>
          <% end %>

          <li><%= link_to "Sign out", destroy_user_session_path %></li>
        </ul>
      <% else %>

        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <li><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %></li>
        </ul>

      <% end %>

      </ul>
    </div>

  </div>
</nav>