config/routes.rb
TownParliament::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => "pages#index"

  get "pages/index"
  get "pages/meeting"
  get "/admin" => "admin/base#index", :as => "admin"

  namespace "admin" do
    resources :users
  end

  resources :acts do
    # HTML AND PDF
    get '/html', to: 'acts#html'
    get '/pdf', to: 'acts#pdf'
  end

  resources :amandments

  post '/create_head_intro', to: 'acts#create_head_intro'
  delete '/destroy_head', to:'acts#destroy_head'

  # REGULATION ROUTES
  post '/prepare_regulation', to: 'acts#prepare_regulation'
  post '/create_regulation', to: 'acts#create_regulation'
  delete '/destroy_regulation', to: 'acts#destroy_regulation'

  # SUBJECT ROUTES
  post '/prepare_subject', to: 'acts#prepare_subject'
  post '/create_subject', to: 'acts#create_subject'
  delete '/destroy_subject', to: 'acts#destroy_subject'

  # CLAUSE ROUTES
  post '/prepare_clause', to: 'acts#prepare_clause'
  post '/create_clause', to: 'acts#create_clause'
  delete '/destroy_clause', to: 'acts#destroy_clause'

  # STANCE ROUTES
  post '/prepare_stance', to: 'acts#prepare_stance'
  post '/create_stance', to: 'acts#create_stance'
  delete '/destroy_stance', to: 'acts#destroy_stance'

  # DOT ROUTES
  post '/prepare_dot', to: 'acts#prepare_dot'
  post '/create_dot', to: 'acts#create_dot'
  delete '/destroy_dot', to: 'acts#destroy_dot'

  # SUBDOT ROUTES
  post '/prepare_subdot', to: 'acts#prepare_subdot'
  post '/create_subdot', to: 'acts#create_subdot'
  delete '/destroy_subdot', to: 'acts#destroy_subdot'

  # PARAGRAPH ROUTES
  post '/prepare_paragraph', to: 'acts#prepare_paragraph'
  post '/create_paragraph', to: 'acts#create_paragraph'
  delete '/destroy_paragraph', to: 'acts#destroy_paragraph'

  # SEARCH SHIT
  get :search, to: 'search#index'
  get :perform_search, to: 'search#perform'

end

app/models/amandment.rb
# == Schema Information
#
# Table name: amandments
#
#  id          :integer          not null, primary key
#  date        :date
#  category    :string           default("wait")
#  content     :text
#  explanation :text
#  rating      :integer
#  owner_id    :integer
#  owner_type  :string
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  status      :string
#

class Amandment < ActiveRecord::Base
  include Elasticsearch::Model
 # include Elasticsearch::Model::Callbacks

  TYPE = ["wait", "accepted", "declined"]

  belongs_to :owner, :polymorphic => true, :foreign_key => :owner_id

  belongs_to :user, -> { where(:name => "alderman") }

  belongs_to :act
end

app/controllers/amandments_controller.rb
class AmandmentsController < ApplicationController
  before_action :set_amandment, only: [:show, :edit, :update, :destroy]

  # GET /amandments
  def index
    @amandments = Amandment.all
  end

  # GET /amandments/1
  def show
    @act = Act.find(@amandment.owner_id)

    redirect_to @act
  end

  # GET /amandments/new
  def new
    @amandment = Amandment.new
    @meeting = Meeting.find(1)
  end

  # GET /amandments/1/edit
  def edit
  end

  # POST /amandments
  def create
    @amandment = Amandment.new(amandment_params)
    @amandment.user = current_user

    if @amandment.save
      redirect_to @amandment, notice: 'Amandment was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /amandments/1
  def update
    if @amandment.update(amandment_params)
      redirect_to @amandment, notice: 'Amandment was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /amandments/1
  def destroy
    client.send_corona_request("/v1/documents?database=Tim22&uri=/amandments/amandment_#{@amandment.id}.xml", :delete)
    @amandment.destroy
    redirect_to amandments_url, notice: 'Amandment was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_amandment
      @amandment = Amandment.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def amandment_params
      params.require(:amandment).permit(:date, :content, :explanation, :rating, :act_id, :owner_id)
    end
end

app/views/amandments/_form.html.erb
<%= form_for(@amandment) do |f| %>
  <% if @amandment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@amandment.errors.count, "error") %> prohibited this amandment from being saved:</h2>

      <ul>
      <% @amandment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/amandments/edit.html.erb
<h1>Editing Amandment</h1>

<%= render 'form' %>

<%= link_to('<button type="button" class="btn btn-info">Show</button>'.html_safe, @amandment) %> |
<%= link_to('<button type="button" class="btn btn-success">Back</button>'.html_safe, amandments_path) %>

app/views/amandments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Amandments</h1>

<table class="table table-striped">
  <thead>
  <th style="width: 70%">Amandment name</th>
  <th style="width: 70%">Act name</th>
  <th style="width: 70%">Show Act</th>
  <th style="width: 5%">Votes</th>
  <th style="width: 5%">Approve</th>
  <th style="width: 5%">Refuse</th>
  <th style="width: 5%">Show</th>
  </thead>
  <tbody>
  <% @amandments.each do |amandment| %>
      <tr>
        <td><%= amandment.explanation %></td>
        <td><%= amandment.act.name %></td>
        <td><%= link_to('<button type="button" class="btn btn-info">Show Act</button>'.html_safe, amandment.act) %></td>
        <td><input type="number" min="-100" max="100"></td>
        <td>
        <% if current_user.assembly_president? %>
          <% unless amandment.status == "approved" %>
            <% if amandment.act.status == "approved" %>

              <%= link_to('<button type="button" class="btn btn-primary">Approve</button>'.html_safe, pages_meeting_path(:amandman => amandment, :akt_id => amandment.act)) %>

            <% else %>

              <%= link_to('<button type="button" class="btn btn-primary disabled">Approve</button>'.html_safe) %>
              <td><%= link_to('<button type="button" class="btn btn-danger">Refuse</button>'.html_safe, amandment, method: :delete, data: { confirm: 'Are you sure?' }) %></td>

            <% end %>
          <% end %>
        <% else %>
          <td></td>
        <% end %>
        </td>
        <td><%= link_to('<button type="button" class="btn btn-info">Show</button>'.html_safe, amandment) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/amandments/new.html.erb
<h1>New Amandment</h1>
<% if !@meeting.status? %>
  <%= render 'form' %>
<% end %>
<%= link_to('<button type="button" class="btn btn-success">Back</button>'.html_safe, amandments_path) %>

app/views/amandments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to('<button type="button" class="btn btn-warning">Edit</button>'.html_safe, edit_amandment_path(@amandment)) %>
<%= link_to('<button type="button" class="btn btn-success">Back</button>'.html_safe, amandments_path) %>