config/routes.rb
TownParliament::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => "pages#index"

  get "pages/index"
  get "pages/meeting"
  get "/admin" => "admin/base#index", :as => "admin"

  namespace "admin" do
    resources :users
  end

  resources :acts do
    # HTML AND PDF
    get '/html', to: 'acts#html'
    get '/pdf', to: 'acts#pdf'
  end

  resources :amandments

  post '/create_head_intro', to: 'acts#create_head_intro'
  delete '/destroy_head', to:'acts#destroy_head'

  # REGULATION ROUTES
  post '/prepare_regulation', to: 'acts#prepare_regulation'
  post '/create_regulation', to: 'acts#create_regulation'
  delete '/destroy_regulation', to: 'acts#destroy_regulation'

  # SUBJECT ROUTES
  post '/prepare_subject', to: 'acts#prepare_subject'
  post '/create_subject', to: 'acts#create_subject'
  delete '/destroy_subject', to: 'acts#destroy_subject'

  # CLAUSE ROUTES
  post '/prepare_clause', to: 'acts#prepare_clause'
  post '/create_clause', to: 'acts#create_clause'
  delete '/destroy_clause', to: 'acts#destroy_clause'

  # STANCE ROUTES
  post '/prepare_stance', to: 'acts#prepare_stance'
  post '/create_stance', to: 'acts#create_stance'
  delete '/destroy_stance', to: 'acts#destroy_stance'

  # DOT ROUTES
  post '/prepare_dot', to: 'acts#prepare_dot'
  post '/create_dot', to: 'acts#create_dot'
  delete '/destroy_dot', to: 'acts#destroy_dot'

  # SUBDOT ROUTES
  post '/prepare_subdot', to: 'acts#prepare_subdot'
  post '/create_subdot', to: 'acts#create_subdot'
  delete '/destroy_subdot', to: 'acts#destroy_subdot'

  # PARAGRAPH ROUTES
  post '/prepare_paragraph', to: 'acts#prepare_paragraph'
  post '/create_paragraph', to: 'acts#create_paragraph'
  delete '/destroy_paragraph', to: 'acts#destroy_paragraph'

  # SEARCH SHIT
  get :search, to: 'search#index'
  get :perform_search, to: 'search#perform'

end

app/models/act.rb
# == Schema Information
#
# Table name: acts
#
#  id         :integer          not null, primary key
#  preambula  :text
#  name       :string
#  state      :string
#  city       :string
#  date       :date
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  status     :string
#

class Act < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  # Akt
  belongs_to :user

  has_many :heads, :dependent => :destroy

  has_many :amandments, :dependent => :destroy
end

app/controllers/acts_controller.rb
class ActsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_act, only: [:show, :edit, :update, :destroy]

  # GET /acts
  def index
    if current_user.citizen?
      @acts = Act.where(:status => "approved")
    else
      @acts = Act.all
    end
  end

  # GET /acts/1
  def show
    @akt = Act.find(params[:id])
    @aktlink = "http://147.91.177.194:8000#{Connection::MarkLogic.new.acts_uri(@akt)}"

    mark_logic = Connection::MarkLogic.new
    act_from_ml = mark_logic.download_act(@akt)

    @act = Nokogiri::XML(act_from_ml)
  rescue
    @act = Transform::ToXml.transform(@akt)
  end

  # GET /acts/new
  def new
    @act = Act.new
    @meeting = Meeting.find(1)
    intit_heads
    redirect_to root_path, notice: 'You cannot add new act when Session is in progress!' and return if @meeting.status
  end

  # GET /acts/1/edit
  def edit
    @amandment = Amandment.new
    @meeting = Meeting.find(1)
    intit_heads
    redirect_to acts_path, notice: 'You cannot edit act when Session is in progress!' and return if @meeting.status
  end

  def html
    @act = Act.find_by_id(params[:act_id])
  end

  def pdf
    @act = Act.find_by_id(params[:act_id])

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "#{@act.name}-#{@act.date}",
               template: '/acts/pdf'
      end
    end
  end

  # POST /acts
  def create
    @act = Act.new(act_params)
    @act.user = current_user

    if @act.save
      session[:heads].each do |head_id|
        Head.find_by_id(head_id).update(act_id: @act.id)
      end

      act_xml = Transform::ToXml.transform(@act).to_s

      mark_logic = Connection::MarkLogic.new
      mark_logic.upload_act(@act, act_xml)

      redirect_to @act, notice: 'Act was successfully created.'
    else
      render :new
    end
  end

  # HEAD STUFF

  def create_head_intro
    if params[:head][:act_id]
      @head = Head.create(category: params[:head][:category],
                        name: params[:head][:name],
                        act_id: params[:head][:act_id])

    else
      @head = Head.create(category: params[:head][:category],
                          name: params[:head][:name])
    end

    add_head_id(@head.id)

    respond_to do |format|
      format.js
    end
  end

  def destroy_head
    # destroy heds here
    @head = Head.find_by_id(params[:id]).destroy
    remove_head_id(@head.id)
    respond_to do |format|
      format.js
    end
  end

  # REGULATION STUFF

  def prepare_regulation
    @head = Head.find_by_id(params[:id])

    respond_to do |format|
      format.js
    end
  end

  def create_regulation
    @regulation = Regulation.create(name: params[:regulation][:name],
                                    definition: params[:regulation][:definition],
                                    head_id: params[:regulation][:head_id])
    respond_to do |format|
      format.js
    end
  end

  def destroy_regulation
    Regulation.find_by_id(params[:id]).destroy
    respond_to do |format|
      format.js
    end
  end

  # SUBJECT STUFF

  def prepare_subject
    @regulation = Regulation.find_by_id(params[:id])

    respond_to do |format|
      format.js
    end
  end

  def create_subject
    @subject = Subject.create(name: params[:subject][:name],
                              regulation_id: params[:subject][:regulation_id])
    respond_to do |format|
      format.js
    end
  end

  def destroy_subject
    Subject.find_by_id(params[:id]).destroy

    respond_to do |format|
      format.js
    end
  end

  # CLAUSE STUFF

  def prepare_clause
    @subject = Subject.find_by_id(params[:id])

    respond_to do |format|
      format.js
    end
  end

  def create_clause
    @clause = Clause.create(name: params[:clause][:name],
                            subject_id: params[:clause][:subject_id])
    respond_to do |format|
      format.js
    end
  end

  def destroy_clause
    Clause.find_by_id(params[:id]).destroy

    respond_to do |format|
      format.js
    end
  end

  # STANCE STUFF

  def prepare_stance
    @clause = Clause.find_by_id(params[:id])

    respond_to do |format|
      format.js
    end
  end

  def create_stance
    @stance = Stance.create(name: params[:stance][:name],
                            content: params[:stance][:content],
                            clause_id: params[:stance][:clause_id])

    respond_to do |format|
      format.js
    end
  end

  def destroy_stance
    Stance.find_by_id(params[:id]).destroy

    respond_to do |format|
      format.js
    end
  end

  # DOT STUFF

  def prepare_dot
    @stance = Stance.find_by_id(params[:id])

    respond_to do |format|
      format.js
    end
  end

  def create_dot
    @dot = Dot.create(name: params[:dot][:name],
                      content: params[:dot][:content],
                      stance_id: params[:dot][:stance_id])

    respond_to do |format|
      format.js
    end
  end

  def destroy_dot
    Dot.find_by_id(params[:id]).destroy

    respond_to do |format|
      format.js
    end
  end

  # SUBDOT STUFF

  def prepare_subdot
    @dot = Dot.find_by_id(params[:id])

    respond_to do |format|
      format.js
    end
  end

  def create_subdot
    @subdot = Subdot.create(name: params[:subdot][:name],
                            content: params[:subdot][:content],
                            dot_id: params[:subdot][:dot_id])

    respond_to do |format|
      format.js
    end
  end

  # PARAGRAPH STUFF

  def prepare_paragraph
    @subdot = Subdot.find_by_id(params[:id])

    respond_to do |format|
      format.js
    end
  end

  def create_paragraph
    @paragraph = Paragraph.create(name: params[:paragraph][:name],
                                  content: params[:paragraph][:content],
                                  subdot_id: params[:paragraph][:subdot_id])

    respond_to do |format|
      format.js
    end
  end

  def destroy_paragraph
    Paragraph.find_by_id(params[:id]).destroy

    respond_to do |format|
      format.js
    end
  end

  # PATCH/PUT /acts/1
  def update
    @act_new = @act.dup

    @act_new.heads = @act.heads

    @act_new.update(act_params)

    session[:heads].each do |head_id|
      head = Head.find(head_id)
      head.update(act_id: @act.id)
      @act_new.heads << head
    end

    act_xml = Transform::ToXml.transform(@act_new).to_s

    mark_logic = Connection::MarkLogic.new
    mark_logic.upload_amandment(@act_new, act_xml)

    respond_to do |format|
      format.js
    end
  end

  # DELETE /acts/1
  def destroy
    @akt = Act.find(params[:id])

    client = Connection::MarkLogic.new.client

    @act.amandments.each do |amandment|
      client.send_corona_request("/v1/documents?database=Tim22&uri=/amandments/amandment_#{amandment.owner_id}.xml", :delete)
      Act.find(amandment.owner_id).destroy
    end

    client.send_corona_request("/v1/documents?database=Tim22&uri=/acts/act_#{@akt.id}.xml", :delete)

    @act.destroy

    redirect_to acts_url, notice: 'Act was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_act
    @act = Act.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def act_params
    params.require(:act).permit(:state, :name, :city, :date, :preambula)
  end

  def to_s
    if @document
      @document.to_xml(:save_with => Nokogiri::XML::Node::SaveOptions::NO_DECLARATION)
    else
      super.to_s
    end
  end

  def intit_heads
    session[:heads] = []
  end

  def add_head_id(id)
    session[:heads] << id
  end

  def remove_head_id(id)
    session[:heads].delete(id)
  end
end

app/views/acts/_clause_modal.html.erb
<div class="modal fade" id="clause-modal-<%= @subject.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4"><strong><h4>Clan</h4></strong></div>
        <div class="col-md-4"></div>
      </div>
      <%= form_for @subject.clauses.build, url: create_clause_path, html: { class:"form-horizontal" }, remote: true do |fc| %>
      <%= fc.hidden_field :subject_id, value: @subject.id %>
      <div class="form-group">
        <div clas="row">
          <label class="col-md-4 control-label" ></label>
           <div class="col-md-4">
            <%= fc.text_field :name, class: "form-control input-md", placeholder: "Naziv",required: true %>
          </div>
        </div>
      </div>

      <!-- dugmad -->
      <br>
      <br>
      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          <span>
            <%= fc.submit "Add Clause", class:"btn btn-danger" %>
          </span>
          <span>
            <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
          </span>
        </div>
        <% end %>
        <br>
      </div>
      <br>
    </div>
  </div>
</div>

app/views/acts/_form.html.erb
<%= form_for @act, html: { class:"form-horizontal" } do |f| %>
  <% if @act.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@act.errors.count, "error") %> prohibited this act from being saved:</h2>
      <ul>
      <% @act.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- star from here -->
  
  <!-- ACT -->

  <div class="form-group">
    <label class="col-md-4 control-label" for="textinput">Drzava</label>  
    <div class="col-md-4">
    <%= f.text_field :state, class: "form-control input-md", required: true %>
   </div>
  </div>
  
  <div class="form-group">
    <label class="col-md-4 control-label" for="textinput">Naziv</label>  
    <div class="col-md-4">
    <%= f.text_field :name, class: "form-control input-md", required: true %>
    </div>
  </div>
  
  <div class="form-group">
    <label class="col-md-4 control-label" for="textinput">Grad</label>  
    <div class="col-md-4">
      <%= f.text_field :city, class: "form-control input-md", required: true %>
    </div>
  </div>
  
  <div class="form-group">
    <label class="col-md-4 control-label" >Datum</label>
    <div class="col-md-4">                     
      <div class='input-group date' id='datetimepicker1'>
        <%= f.date_select(:date, :order => [:day, :month, :year], required: true) %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <label class="col-md-4 control-label" for="textarea">Preambula</label>
    <div class="col-md-4">                     
      <%= f.text_area :preambula, class: "form-control input-md", required: true %>
    </div>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

  <!-- GLAVE -->
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="form-group">
        <label class="control-label" >Uvodni dio</label>
          <button type="button" class="btn btn-primary  info-head-button" data-toggle="modal" data-target="#intro-head-modal">Add glava</button>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col-md-8 col-md-offset-4 intro-heads-place">
    </div>
  </div>

    <!-- GLAVE -->
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="form-group">
        <label class="control-label" >Glavni dio</label>
          <button type="button" class="btn btn-primary main-head-button" data-toggle="modal" data-target="#main-head-modal">Add glava</button>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col-md-8 col-md-offset-4 main-heads-place">
    </div>
  </div>

    <!-- GLAVE -->
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="form-group">
        <label class="control-label" >Zavrsni dio</label>
          <button type="button" class="btn btn-primary end-head-button" data-toggle="modal" data-target="#end-head-modal">Add glava</button>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col-md-8 col-md-offset-4 end-heads-place">
    </div>
  </div>






  <%= render "head_introduction_modal" %>
  <%= render "head_main_modal" %>
  <%= render "head_end_modal" %>
  <div class="modal-place"></div>

app/views/acts/_head_end_modal.html.erb
<div class="modal fade" id="end-head-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4"><strong><h4>Glavni deo - naziv glave</h4></strong></div>
        <div class="col-md-4"></div>
      </div>
      <%= form_for @act.heads.build, url: create_head_intro_path, remote: true do |fgi| %>
      <%= fgi.hidden_field :category, value: Head::TYPES[2] %>
      <div class="form-group">
        <div clas="row">
          <label class="col-md-4 control-label" ></label>
           <div class="col-md-4">
            <%= fgi.text_field :name, class: "form-control input-md", required: true %>
          </div>
        </div>
      </div>
      <!-- dugmad -->
      <br>
      <br>
      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          <span>
            <%= fgi.submit "Add Glava", class:"btn btn-danger" %>
          </span>
          <span>
            <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
          </span>
        </div>
        <% end %>
        <br>
      </div>
      <br>
    </div>
  </div>
</div>

app/views/acts/_head_info.html.erb
<div id="introduction-head-<%= @head.id %>">
  Glava: <%= @head.name %> 

  <%= link_to "Delete", destroy_head_path(id: @head.id), method:"delete", data: {confirm: "Are you sure?"}, class: "btn btn-danger",remote: true %>

  <%= link_to "Add Odredba", prepare_regulation_path(id: @head.id), method:"post",class: "btn btn-primary", remote: true %>
  
  <% @head.regulations.each do |regulation| %>
  	<%= render partial: "regulation_info", locals: { "@regulation": regulation } %>
  <% end %>
</div>

app/views/acts/_regulation_info.html.erb
<div id="regulation-<%= @regulation.id %>">
  Odredba: <%= @regulation.name %> 

  <%= link_to "Delete", destroy_regulation_path(id: @regulation.id), method:"delete", data: {confirm: "Are you sure?"}, class: "btn btn-danger",remote: true %>

  <%= link_to "Add Predmet", prepare_subject_path(id: @regulation.id) , method:"post",class: "btn btn-primary", remote: true %>

  <% @regulation.subjects.each do |subject| %>
  	<%= render partial: "subject_info", locals: { "@subject": subject } %>
  <% end %>
</div>

app/views/acts/_subdot_info.html.erb
<div id="subdot-<%= @subdot.id %>">
  Podtacka: <%= @subdot.name %> 

  <%= link_to "Delete", destroy_subdot_path(id: @subdot.id), method:"delete", data: {confirm: "Are you sure?"}, class: "btn btn-danger",remote: true %>

  <%= link_to "Add Paragraf", prepare_paragraph_path(id: @subdot.id) , method:"post", class: "btn btn-primary", remote: true %>

  <% @subdot.paragraphs.each do |paragraph| %>
  	<%= render partial: "paragraph_info", locals: { "@paragraph": paragraph } %>
  <% end %>
</div>

app/views/acts/_subdot_modal.html.erb
<div class="modal fade" id="subdot-modal-<%= @dot.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4"><strong><h4>Podtacka</h4></strong></div>
        <div class="col-md-4"></div>
      </div>
      <%= form_for @dot.subdots.build, url: create_subdot_path, html: { class:"form-horizontal" }, remote: true do |fsd| %>
      <%= fsd.hidden_field :dot_id, value: @dot.id %>
      <div class="form-group">
        <div clas="row">
          <label class="col-md-4 control-label" ></label>
           <div class="col-md-4">
            <%= fsd.text_field :name, class: "form-control input-md", placeholder: "Naziv",required: true %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div clas="row">
          <label class="col-md-4 control-label" ></label>
           <div class="col-md-4">
            <%= fsd.text_area :content, class: "form-control input-md", placeholder: "Sadrzaj",required: true %>
          </div>
        </div>
      </div>

      <!-- dugmad -->
      <br>
      <br>
      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          <span>
            <%= fsd.submit "Add Podtacka", class:"btn btn-danger" %>
          </span>
          <span>
            <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
          </span>
        </div>
        <% end %>
        <br>
      </div>
      <br>
    </div>
  </div>
</div>

app/views/acts/_subject_info.html.erb
<div id="subject-<%= @subject.id %>">
  Predmet: <%= @subject.name %> 

  <%= link_to "Delete", destroy_subject_path(id: @subject.id), method:"delete", data: {confirm: "Are you sure?"}, class: "btn btn-danger",remote: true %>

  <%= link_to "Add Clan", prepare_clause_path(id: @subject.id) , method:"post", class: "btn btn-primary", remote: true %>

  <% @subject.clauses.each do |clause| %>
  	<%= render partial: "clause_info", locals: { "@clause": clause } %>
  <% end %>
</div>

app/views/acts/create_subdot.js.erb
$("#subdot-modal-<%= @subdot.dot_id %>").modal('toggle');
$("#subdot_name").val("");
$("#subdot_content").val("");
$('#dot-<%= @subdot.dot_id %>').append("<%= j render(:partial => 'subdot_info') %>");

app/views/acts/destroy_stance.js.erb
$("#stance-<%= params[:id] %>").remove();

app/views/acts/index.html.erb
<p id="notice"><%= notice %></p>

<% if @acts.empty? %>
  <h3>Sorry, there are no acts in the database :(</h3>
  <p>Ask some alderman to add them :)</p>
<% else %>
  <h1>Listing Acts</h1>

  <table class="table table-striped">
    <thead>
      <th style="width: 70%">Act name</th>
      <th style="width: 5%">Approved</th>
      <th style="width: 5%">Show</th>
      <th style="width: 5%">Edit</th>
      <th style="width: 5%">Destroy</th>
      <th style="width: 5%">HTML</th>
      <th style="width: 5%">PDF</th>
    </thead>
    <tbody>
      <% @acts.each do |act| %>

        <tr>
          <td><%= act.name %></td>

          <% if act.status %>
            <td><a class="btn btn-success"><span class="glyphicon glyphicon-ok"></span></a></td>
          <% else %>
            <td><a class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span></a></td>
          <% end %>
          <td><%= link_to('<button type="button" class="btn btn-info">Show</button>'.html_safe, act) %></td>

          <td>
            <% if current_user.alderman? %>
              <%= link_to('<button type="button" class="btn btn-warning">Edit</button>'.html_safe, edit_act_path(act)) %>
            <% end %>
          </td>

          <% if act.user.try(:id) == current_user.id %>

            <td><%= link_to('<button type="button" class="btn btn-danger">Destroy</button>'.html_safe, act, method: :delete, data: { confirm: 'Are you sure?' }) %></td>

          <% else %>

            <td></td>

          <% end %>

          <td> <%= link_to "HTML", act_html_path(act), class:"btn btn-info" %> </td>
          <td> <%= link_to "PDF", act_pdf_path(act) <<'.pdf', class:"btn btn-warning", :target => "_blank" %> </td>
         </tr>

      <% end %>
    </tbody>
  </table>

  <br>

<% end %>

<% if current_user.alderman? %>
  <%= link_to('<button type="button" class="btn btn-primary">New Act</button>'.html_safe, new_act_path) %>
<% end %>

app/views/acts/prepare_regulation.js.erb
$('.modal-place').append("<%= j render(:partial => 'regulation_modal') %>");
$("#regulation_name").val("");
$("#regulation_definition").val("");
$('#regulation-modal-<%= @head.id %>').modal("toggle");

app/views/acts/prepare_subject.js.erb
$('.modal-place').append("<%= j render(:partial => 'subject_modal') %>");
$("#subject_name").val("");
$('#subject-modal-<%= @regulation.id %>').modal("toggle");

app/views/acts/show.html.erb
<h1>Act: <i><%= @akt.name %></i></h1>

<h2>MarkLogic</h2>

<h6><textarea class="form-control" rows="20"><%= @act %></textarea></h6>

<%= link_to('<button type="button" class="btn btn-primary">Show as XML</button>'.html_safe, @aktlink) %>
<%= link_to('<button type="button" class="btn btn-warning">Edit</button>'.html_safe, edit_act_path(@akt)) %>
<%= link_to('<button type="button" class="btn btn-success">Back</button>'.html_safe, acts_path) %>

<% if @akt.amandments.empty? || current_user.citizen? %>
  <h1>No amandment for this act</h1>
<% else %>
  <h1>Listing Amandments for this act</h1>

  <table class="table table-striped">
    <thead>
    <th style="width: 70%">Amandment name</th>
    <th style="width: 70%">Act name</th>
    <th style="width: 70%">Show Act</th>
    <th style="width: 5%">Votes</th>
    <th style="width: 5%">Approve</th>
    <th style="width: 5%">Refuse</th>
    <th style="width: 5%">Show</th>
    </thead>
    <tbody>
    <% @akt.amandments.each do |amandment| %>
        <tr>
          <td><%= amandment.explanation %></td>
          <td><%= amandment.act.name %></td>
          <td><%= link_to('<button type="button" class="btn btn-info">Show Act</button>'.html_safe, amandment.act) %></td>
          <td><input type="number" min="-100" max="100"></td>
          <td>
          <% if current_user.assembly_president? %>
            <% unless amandment.status == "approved" %>
              <% if amandment.act.status == "approved" %>

                <%= link_to('<button type="button" class="btn btn-primary">Approve</button>'.html_safe, pages_meeting_path(:amandman => amandment, :akt_id => amandment.act)) %>

              <% else %>

                <%= link_to('<button type="button" class="btn btn-primary disabled">Approve</button>'.html_safe) %>
                <td><%= link_to('<button type="button" class="btn btn-danger">Refuse</button>'.html_safe, amandment, method: :delete, data: { confirm: 'Are you sure?' }) %></td>

              <% end %>
            <% end %>
          <% else %>
            <td></td>
          <% end %>
          </td>
          <td><%= link_to('<button type="button" class="btn btn-info">Show</button>'.html_safe, amandment) %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
<% end %>